/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Word } from "../types";
import { renderFront, renderBack } from "./cardTemplates";

/**
 * Prepares a field for TSV export by removing tabs and newlines,
 * ensuring columns and rows are delimited correctly.
 */
export function escapeTsvField(field: string | undefined | null): string {
  if (!field) return "";
  // Remove tab characters and newlines to keep each record strictly on a single line
  return field.replace(/\t/g, " ").replace(/\r?\n/g, " ").trim();
}

/**
 * Exports words as a tab-separated TXT file and triggers a browser download.
 * Columns: Word, Translation, IPA, Example, Explanation, Book, Context
 */
export function exportToTsv(words: Word[], filename: string = "kindle_anki_export.txt"): void {
  const headers = ["Word", "Translation", "IPA", "Example", "Explanation", "Book Title", "Original Kindle Context"];
  
  const rows = words.map((w) => [
    escapeTsvField(w.word),
    escapeTsvField(w.translation),
    escapeTsvField(w.ipa),
    escapeTsvField(w.example),
    escapeTsvField(w.explanation),
    escapeTsvField(w.bookTitle),
    escapeTsvField(w.context)
  ]);

  const tsvContent = [
    "#separator:tab",
    "#html:true",
    "# " + headers.join("\t"),
    ...rows.map((row) => row.join("\t"))
  ].join("\n");
  
  // Use UTF-8 BOM so Russian characters and other Non-ASCII UTF-8 characters render perfectly
  const blob = new Blob(["\uFEFF" + tsvContent], { type: "text/plain;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute("download", filename);
  link.style.visibility = "hidden";
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Exports words using styled HTML generated by the universal card template into a 2-column TSV (Front/Back) TXT file.
 */
export function exportToTsvStyled(
  words: Word[],
  filename: string = "kindle_anki_styled.txt"
): void {
  const headers = ["Front", "Back"];

  const rows = words.map((w) => [
    escapeTsvField(renderFront(w)),
    escapeTsvField(renderBack(w)),
  ]);

  const tsvContent = [
    "#separator:tab",
    "#html:true",
    "# " + headers.join("\t"),
    ...rows.map((row) => row.join("\t"))
  ].join("\n");

  const blob = new Blob(["\uFEFF" + tsvContent], { type: "text/plain;charset=utf-8;" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute("download", filename);
  link.style.visibility = "hidden";

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}


